import bases from "@/assets/images/clover/base";
import * as cosmetics from "@/assets/images/clover/cosmetics";

/**
 * Type of a Clover.
 */
export enum CloverType {
    Regular,
    Hero,
}

/**
 * A type of job a Clover can have.
 */
export enum Job {
    Blacksmith,
    FactoryWorker,
    Mechanic,
    Miner,
    Lumberjack,
    Scientist,
    Diver,
    Astronaut,
    Cultist,
    Investor,
    Alien,
    Hazmat,
    Wizard,
    Knight,
    Sketch,
    Peak,
}

/**
 * Cosmetical configuration of a Clover Job.
 */
export interface JobConfig {
    bases?: Record<CloverType, string[]>;
    extras?: string[];
    cosmetics?: string[];
}

/**
 * Mapping for Clover jobs to image URLs.
 */
export const Jobs: { [type in Job]: JobConfig } = {
    [Job.Miner]: {
        bases: bases.regular,
        extras: [cosmetics.lips],
        cosmetics: [cosmetics.miner],
    },
    [Job.Lumberjack]: {
        bases: bases.regular,
        cosmetics: [cosmetics.lumberjack],
    },
    [Job.Blacksmith]: {
        bases: bases.regular,
        cosmetics: [cosmetics.blacksmith],
    },
    [Job.Mechanic]: {
        bases: bases.regular,
        extras: [cosmetics.lips],
        cosmetics: [cosmetics.mechanic],
    },
    [Job.FactoryWorker]: {
        bases: bases.regular,
        extras: [cosmetics.lips],
        cosmetics: [cosmetics.factory_worker],
    },
    [Job.Diver]: {
        bases: bases.regular,
        extras: [cosmetics.lips],
        cosmetics: [cosmetics.scuba],
    },
    [Job.Scientist]: {
        bases: bases.regular,
        extras: [cosmetics.lips],
        cosmetics: [cosmetics.scientist],
    },
    [Job.Investor]: {
        bases: bases.regular,
        cosmetics: [cosmetics.investor],
    },
    [Job.Hazmat]: {
        bases: bases.hazmat,
    },
    [Job.Knight]: {
        bases: bases.regular,
        cosmetics: [cosmetics.knight],
    },
    [Job.Cultist]: {
        bases: bases.regular,
        extras: [cosmetics.lips],
        cosmetics: [cosmetics.cultist],
    },
    [Job.Wizard]: {
        bases: bases.regular,
        cosmetics: [cosmetics.wizard],
    },
    [Job.Astronaut]: {
        bases: bases.regular,
        extras: [cosmetics.lips],
        cosmetics: [cosmetics.astronaut],
    },
    [Job.Alien]: {
        bases: bases.alien,
    },
    [Job.Sketch]: {
        bases: bases.sketch,
    },
    [Job.Peak]: {
        bases: bases.peak,
    },
};

/**
 * The potential name pool for Clovers.
 */
export const names = [
    "Kuriimu",
    "Aldi",
    "Xander",
    "Boyong",
    "Bannana Bread",
    "Doomei",
    "EcchiArtistIdk",
    "ISneeze",
    "Khris",
    "Leno",
    "Matze",
    "Nekomimi",
    "Nilok",
    "Nutman",
    "Endor",
    "Pluto",
    "Robotic",
    "Skumm",
    "TsunekoFuwakage",
    "frammie",
    "VDruid0",
    "Firebreath",
    "Nova Dysnomia",
    "Awysu",
    "Sway Nay",
    "Hydrattler",
    "Necrozma",
    "ArchiveAnon",
    "EB",
    "MiiMoo",
    "GhostClown",
    "Sate",
    "Hidrogenario",
    "Yann",
    "Shiru kazuki",
    "samRye",
    "DWraith23",
    "SleepingSlime",
    "Lion",
    "Koudelka",
    "Lifeline",
    "Messed Up Brainspike",
    "Nutella",
    "Dani",
    "CloneofShade",
    "Emilia",
    "Tsuneko Fuwakage",
    "Akuneko Zero",
    "Liam Nii-san",
    "Rellikai",
    "Kuteko",
    "jake",
    "npc_igarashi",
    "6thMagic",
    "Aekrid",
    "Alcachofa",
    "Alice C. Alucard",
    "Andre Scarlet",
    "Angry Sandwich",
    "Archive Anon",
    "Ardamax",
    "Awing",
    "Babbel",
    "Balthros",
    "Based Department",
    "Big Kusa",
    "Bobby Nash",
    "Bruh Dude man",
    "Carlos",
    "Cat🔑",
    "Cement Pinata",
    "ChainDuel",
    "Cilli 02",
    "Claymore 155",
    "Colson M",
    "Cosmic Explode",
    "Cturne",
    "Daniel Palmqvist",
    "Dante Lenister",
    "DayLightKnight",
    "Delicious Sandwich",
    "DepudeeRLD",
    "Diego Flores Gajardo",
    "Dkimm 233",
    "Doctor Bob",
    "Doctor P",
    "Doodler",
    "Empathy",
    "Everfall",
    "FATDADDYSACK",
    "FireballStarfish",
    "Flojo",
    "Floran🧚🌱",
    "FranklyAstounded",
    "Frobledo",
    "Frosty-",
    "Gabriel Luthien",
    "Gerardo Sánchez",
    "Ghost Clown🎉",
    "GoddessNepgear",
    "Gotz the Ironhand",
    "GraMMa",
    "GreyDeity",
    "Hammerchuckery",
    "Helius Universe",
    "Herbie Cucumber 🎉",
    "HorrorMoose",
    "Hrotriks (Mumu's soul meal)",
    "ImmortalInflames",
    "Isaac",
    "ItsAhelbitz",
    "ItsCase",
    "JTsoppy137",
    "James Beans",
    "Jeffrojeff",
    "Jordan Grange",
    "Kaato カアト",
    "Kaigai Aniki",
    "Kamori Asani",
    "Kek I. Stan",
    "Kevin Bacon",
    "Kexos🍀🔑",
    "Kiran bob",
    "Kiyo",
    "Kjeld",
    "Koudellka",
    "Kurt Hutchison",
    "Kyle G",
    "Kyomu",
    "Lazm",
    "Lion of the Mist",
    "Lu2304",
    "Luis Medina",
    "Macman71299",
    "Mad Angry",
    "Maedara",
    "Mehscope",
    "Mero Nya Ch.",
    "Mochi Mochi",
    "MonsterL",
    "Mr.Mc.spliff",
    "MrObby",
    "Mrmctrustyguy",
    "Nark101",
    "Neia",
    "NekoMyraMia",
    "Nihilist",
    "Norberto Martin",
    "NotoriousBSG82",
    "Nutella24",
    "OGcthulhu",
    "Oleksandr Tarasov",
    "PW",
    "Panda",
    "Pokosaur Rising 🔑",
    "Poncho",
    "Professor Guapo",
    "PunishedToki",
    "Restlezz",
    "Ryechu",
    "SA 👻🎉",
    "SCJ",
    "Sable Silly",
    "Sander",
    "Saul",
    "ShadowsCrow",
    "Sharamper",
    "Sketch-Lion",
    "SofaKing1337",
    "Some Body",
    "Spudlyman",
    "Straps",
    "Tama Mochi",
    "Taz 💪🪄",
    "Tempie",
    "Teto V",
    "That Guy Raz",
    "That Rheeve Guy",
    "The Best badness420k",
    "The McGrizzle",
    "TheGrassay",
    "ThebesthitsCD",
    "ThermalGeist",
    "ThomasPrime",
    "Toucan Pam",
    "Tyler Von Mehz",
    "Urso Metamorfo",
    "Ven",
    "XTEcchi",
    "Xiazee",
    "Yalla Jalla",
    "Yono Kino",
    "acertainsomeone",
    "bob oboz",
    "boyong",
    "entropy",
    "epigeios",
    "gavinfree none",
    "generalha",
    "heyheyalaska",
    "holystars",
    "iamwinter17",
    "imnutass",
    "johny",
    "johnzero7",
    "kari",
    "kawaatime",
    "kirakira same🤍",
    "lauza",
    "løu",
    "m2x2 P",
    "neyyko",
    "niyo1j39",
    "peppament",
    "rubyruby",
    "sahelanthropus",
    "shua🔑",
    "tacticalelf",
    "xXInkLeeXx",
    "zipli",
    "🎉Design&Conker🎉",
];
