name: Build

on:
    pull_request:

permissions:
    contents: read
    packages: read

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Dependencies
              run: npm install

            - name: Build
              run: npm run build
