name: Lint

on:
    push:
    pull_request:

permissions:
    checks: write

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Dependencies
              run: npm install

            - name: Run linters
              uses: wearerequired/lint-action@v1
              with:
                  eslint: true
                  eslint_extensions: ts,tsx
                  prettier: true
